### ISSUE TITLE
yarn test failed

### ISSUE THREAD

**Issue by wuyuyue** [cryptape/cita-truffle-migrate#13]
```
yarn test
yarn run v1.13.0
$ mocha


(node:45260) V8: C:\Users\wu\Desktop\project\cita-truffle-migrate\node_modules\solc\soljson.js:3 Invalid asm.js: Invalid member of stdlib
  Abstractions
Error in deploy: Error: sendDeployContract failed
Error: Returned error: InvalidVersion
    at contract.deploy.send.catch (C:\Users\wu\Desktop\project\cita-truffle-migrate\dist\utils\appchain.js:49:13)
    1) should set the transaction hash of contract instantiation
Error in deploy: Error: sendDeployContract failed
Error: Returned error: InvalidVersion
    at contract.deploy.send.catch (C:\Users\wu\Desktop\project\cita-truffle-migrate\dist\utils\appchain.js:49:13)
    2) should get and set values via methods and get values via .call or .send
Error in deploy: Error: sendDeployContract failed
Error: Returned error: InvalidVersion
    at contract.deploy.send.catch (C:\Users\wu\Desktop\project\cita-truffle-migrate\dist\utils\appchain.js:49:13)
    3) shouldn't synchronize constant functions

  Cloning
    √ produces two distinct objects

  Custom options
    √ allows custom options

  Deprecated json keys
    √ successfully turns `unlinked_binary` into bytecode

  Library linking
    4) leaves binary unlinked initially
    5) links first library properly
    6) links second library properly
    7) allows for selective relinking


  3 passing (4s)
  7 failing

  1) Abstractions
       should set the transaction hash of contract instantiation:
     Error: sendDeployContract failed
Error: Returned error: InvalidVersion
      at contract.deploy.send.catch (dist\utils\appchain.js:49:13)

  2) Abstractions
       should get and set values via methods and get values via .call or .send:
     Error: sendDeployContract failed
Error: Returned error: InvalidVersion
      at contract.deploy.send.catch (dist\utils\appchain.js:49:13)

  3) Abstractions
       shouldn't synchronize constant functions:
     Error: sendDeployContract failed
Error: Returned error: InvalidVersion
      at contract.deploy.send.catch (dist\utils\appchain.js:49:13)

  4) Library linking
       leaves binary unlinked initially:
     Error: LibraryExample has no network id set, cannot lookup artifact data. Either set the network manually using LibraryExample.setNetwork(), run LibraryExample.detectNetwork(), or use new(), at() or deployed() as a thenable which will detect the network automatically.
      at Function.links (dist\contract\contract.js:566:13)
      at Function.getter (dist\contract\contract.js:280:45)
      at Function.binary (dist\contract\contract.js:620:51)
      at Function.getter (dist\contract\contract.js:280:45)
      at Context.<anonymous> (test\linking.js:51:27)

  5) Library linking
       links first library properly:
     Error: LibraryExample has no network id set, cannot lookup artifact data. Either set the network manually using LibraryExample.setNetwork(), run LibraryExample.detectNetwork(), or use new(), at() or deployed() as a thenable which will detect the network automatically.
      at Function.network (dist\contract\contract.js:477:13)
      at Function.getter (dist\contract\contract.js:280:45)
      at Function.link (dist\contract\contract.js:220:8)
      at Context.<anonymous> (test\linking.js:55:20)

  6) Library linking
       links second library properly:
     Error: LibraryExample has no network id set, cannot lookup artifact data. Either set the network manually using LibraryExample.setNetwork(), run LibraryExample.detectNetwork(), or use new(), at() or deployed() as a thenable which will detect the network automatically.
      at Function.network (dist\contract\contract.js:477:13)
      at Function.getter (dist\contract\contract.js:280:45)
      at Function.link (dist\contract\contract.js:220:8)
      at Context.<anonymous> (test\linking.js:65:20)

  7) Library linking
       allows for selective relinking:
     Error: LibraryExample has no network id set, cannot lookup artifact data. Either set the network manually using LibraryExample.setNetwork(), run LibraryExample.detectNetwork(), or use new(), at() or deployed() as a thenable which will detect the network automatically.
      at Function.links (dist\contract\contract.js:566:13)
      at Function.getter (dist\contract\contract.js:280:45)
      at Function.binary (dist\contract\contract.js:620:51)
      at Function.getter (dist\contract\contract.js:280:45)
      at Context.<anonymous> (test\linking.js:75:27)



error Command failed with exit code 7.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by wuyuyue** [comment]
fixed by #14
